package com.gal;

import com.gal.model.*;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import jakarta.persistence.Query;

import java.time.LocalDate;
import java.util.List;


// create an entity project (auto created using sequence strategy) projectid), title, client, startdate, enddate, budget,
// one to one mapping
// projectmanager

//add 5 projects to db using code only



//Capgemini
//hibernate_training
//trainee : id supersetid autogenerated
//batches
//trainer
//content : java, python, dotnet
//venue galgotia university ,
//attendance/exam date marks


public class EntityManagerFactoryConnectionMain {

    private static EntityManagerFactory emf = null;
    private static EntityManager em = null;

    public static EntityManagerFactory getEntityManagerFactory(){
        if(emf == null || !emf.isOpen()){
            emf = Persistence.createEntityManagerFactory("company_db_pu");
        }
        System.out.println(emf);
        return emf;
    }
    public static EntityManager getEntityManager(){
        if(emf == null){
            getEntityManagerFactory();
        }
        if(em ==null || !em.isOpen()){
            em = emf.createEntityManager();
        }
        return em;
    }
    public static void main(String[] args) {
        EntityManager em = EntityManagerFactoryConnectionMain.getEntityManager();
//
//        Item item = new Item(0, "electronics", "laptop", 120000.0);
//        em.getTransaction().begin();
//        em.persist(item);
//        Parking p1 = new Parking(0,  "A101");
//        Parking p2 = new Parking(0,"B202");
//        em.persist(p1);
//        em.persist(p2);
//
//        System.out.println(p1);
//        System.out.println(p2);
//
//        Department dept = em.find(Department.class, 10);
//
//        Employee emp = new Employee();
//        emp.setFirstName("Alice");
//        emp.setDepartment(dept);
//
//        em.persist(emp);
//        em.getTransaction().commit();
//        Query query = em.createQuery(
//                "SELECT e FROM Employee e WHERE e.firstName LIKE 'A%'"
//        );
//        List<Employee> list = query.getResultList();
//        for (Employee e : list) {
//            System.out.println(e);
//        }
//        em.close();

        em.getTransaction().begin();

        // 🔥 Create Department
        Department dept = em.find(Department.class, 60);

        if (dept == null) {
            dept = new Department(60, "AI Research", 100);
            em.persist(dept);
        }
        Employee m1 = new Employee(301, "Aman", "Sharma", "aman@gmail.com",
                "9999991111", LocalDate.now(),
                "Project Manager", 80000,
                null, "Delhi", dept);

        Employee m2 = new Employee(302, "Riya", "Singh", "riya@gmail.com",
                "9999992222", LocalDate.now(),
                "Project Manager", 82000,
                null, "Noida", dept);

        Employee m3 = new Employee(303, "Karan", "Mehta", "karan@gmail.com",
                "9999993333", LocalDate.now(),
                "Project Manager", 85000,
                null, "Gurgaon", dept);

        Employee m4 = new Employee(304, "Neha", "Kapoor", "neha@gmail.com",
                "9999994444", LocalDate.now(),
                "Project Manager", 83000,
                null, "Delhi", dept);

        Employee m5 = new Employee(305, "Vikram", "Rao", "vikram@gmail.com",
                "9999995555", LocalDate.now(),
                "Project Manager", 87000,
                null, "Noida", dept);

        em.persist(m1);
        em.persist(m2);
        em.persist(m3);
        em.persist(m4);
        em.persist(m5);
        Project pr1 = new Project("AI Bot", "Google",
                LocalDate.now(), LocalDate.now().plusMonths(6),
                500000, m1);

        Project pr2 = new Project("ML System", "Amazon",
                LocalDate.now(), LocalDate.now().plusMonths(8),
                800000, m2);

        Project pr3 = new Project("Analytics Tool", "Microsoft",
                LocalDate.now(), LocalDate.now().plusMonths(5),
                400000, m3);

        Project pr4 = new Project("Data Platform", "Meta",
                LocalDate.now(), LocalDate.now().plusMonths(10),
                900000, m4);

        Project pr5 = new Project("Automation AI", "Tesla",
                LocalDate.now(), LocalDate.now().plusMonths(7),
                700000, m5);

        em.persist(pr1);
        em.persist(pr2);
        em.persist(pr3);
        em.persist(pr4);
        em.persist(pr5);

        em.getTransaction().commit();
        em.close();
        emf.close();

        System.out.println("✅ Data Inserted Successfully");
        em.close();
    }
}



//capgemini
